### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by cahartin** [JGCRI/Hector_COMBO#7]
[task_list.docx](https://github.com/JGCRI/Hector_COMBO/files/3606036/task_list.docx)

**Comment by cahartin** [comment]
- [x] trace `temp_co2` to see if ocean or atmo temp

- [x]  get loop working in `scengen_extractv5`

- [x] make pattern files for other years

- [x] read in NA's instead of -999

**Comment by abigailsnyder** [comment]
- [x] Update pattern files with Hector values in terms of degC and not change in degC

**Comment by abigailsnyder** [comment]
- [x] update COMBO's read in functions so that it works with Matlab versions both before and after R2019a

- [ ] shift over grid cell counting for FL to account for the 3 FL sites classified as land on 2.5deg grid ? 

- [ ] PR rec values missing from tab `values_all` of the file `User_inputsv5.xls` - these values come from the EPA with COMBO, so the code appears to just not work for PR. 

- [ ]

**Comment by abigailsnyder** [comment]
trace `temp_co2` to see if ocean or atmo temp: 
traced `temp_co2` created by `scengen_extractv5` _backwards_ to see where the `baseT` (that our patternscaled changes in SST are added to) comes from. It's the Reynolds data which is SST, I believe. 
So `temp_co2` is a table of year, co2, degC local SST actual values. 

I still don't understand how they have no `NA` values in the .OUT files - clearly did some kind of overwriting with numerical entries, probably for the same reason we use -999 instead of `NA` values; the only confusing part is that they _aren't_ dropping those land cells (based on all the land masking code being commented out). So those values do go into the average temperature change in the 3x3 box and therefore have some kind of reliable meaning.

**Comment by abigailsnyder** [comment]
get loop working in `scengen_extractv5`: 
Loop is now working in `scengen_extractv5` locally for me (Commit https://github.com/JGCRI/Hector_COMBO/commit/6c264a01aa2e9f099510508f1b2ca2f795de974f); Because of upstream deprecated Matlab functions, I had to make up some values to test it and I can't test how the inputs go downstream.

**Comment by abigailsnyder** [comment]
read in `NA` instead of `-999`: Commit https://github.com/JGCRI/Hector_COMBO/commit/cddf17e8aedb80bce48828e6be2487b6597079ad effectively does this.
Now `scengen_extractv5` ignores any -999 values in a 3x3 box of interest.  So if there's one of the 9 grid cells that is -999, `avg` will just be the mean of the other 8 numbers. Not as elegant as getting it to read in NAs instead of -999 and ignore, but done for now.

**Comment by cahartin** [comment]
Nice thanks!
